import type { Metadata } from "next";
import Link from 'next/link'
export const metadata: Metadata = {
  title: "analytics-layout",
  description: "Generated by create next app",
};

export default function Page({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div>
       <p>我是 analytics-layout页面</p>
       <nav>
           <Link href="/page-views">Page Views</Link>
           <br/>
           <Link href="/visitors">Visitors</Link>
       </nav>
       {children}
   </div>
  );
}
